install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco install -y ghc --version 8.0.2
  - refreshenv

  - cabal update
  - cabal install alex happy
  - cabal install --only-dependencies --enable-tests

build_script:
  - cabal configure --ghc-option=-Werror --enable-tests
  - cabal build
  - cabal test
